#!/usr/bin/env bash
# shellcheck disable=SC2034 # sourced by qgate.sh; lane assignments are consumed there.
# Generated by install-gate.sh. Regenerate rather than hand-editing.
QG_STACKS=shell\ common
L_FMT_shell=git\ diff\ --check\ \&\&\ git\ diff\ --cached\ --check\ \&\&\ git\ diff\ HEAD~1\ HEAD\ --check
L_LINT_shell=shellcheck\ \$\(repo_files\ \|\ grep\ -E\ \'\\.sh\$\'\)
L_UNIT_shell=bats\ tests
L_ACCEPT_shell=bats\ tests
L_FUZZ_SMOKE_shell=bash\ scripts/fuzz-\*.sh
L_SECRETS_common=gitleaks\ detect\ --no-banner\ --redact
L_SAST_shell=shellcheck\ \$\(repo_files\ \|\ grep\ -E\ \'\\.sh\$\'\)
