#!/usr/bin/env bash
# Quality gate runner. Generated by dmj:enforcing-quality-gates.
# Usage: bash qgate.sh [--fast|--merge|--deep]   (default --merge)
#
# A lane whose tool is missing reports UNAVAILABLE. --merge and --deep refuse
# to go green while any lane is UNAVAILABLE and unwaived, because a gate that
# silently skips is a gate that lies.
set -uo pipefail
cd "$(dirname "$0")" || exit 1
. ./qgate.config.sh
if [ ! -f ./.qgate-lanes.sh ]; then
  echo "qgate: missing .qgate-lanes.sh (the generated lane manifest)." >&2
  echo "qgate: regenerate it: bash install-gate.sh" >&2
  exit 1
fi
. ./.qgate-lanes.sh
TIER="${1:---merge}"
FAILED=0; UNAVAIL=0; RAN=0

c_pass=$'\033[32m'; c_fail=$'\033[31m'; c_warn=$'\033[33m'; c_dim=$'\033[2m'; c_off=$'\033[0m'
[ -t 1 ] || { c_pass=; c_fail=; c_warn=; c_dim=; c_off=; }

waived() { case "$WAIVERS" in *"$1:"*) return 0 ;; *) return 1 ;; esac; }
repo_files() {
  git ls-files --cached --others --exclude-standard 2>/dev/null \
    | grep -Ev '(^|/)\.git(/|$)|(^|/)\.dmj-tools(/|$)' || true
}
run_lane_command() {
  local command="$1" output_file="$2" pid deadline
  ( eval "$command" ) >"$output_file" 2>&1 &
  pid=$!
  deadline=$((SECONDS + ${LANE_TIMEOUT_SECONDS:-120}))
  while kill -0 "$pid" 2>/dev/null; do
    if [ "$SECONDS" -ge "$deadline" ]; then
      kill "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
      printf 'qgate: lane timed out after %ss\n' "${LANE_TIMEOUT_SECONDS:-120}" >"$output_file"
      return 124
    fi
    sleep 0.1
  done
  wait "$pid"
}
# Is the tool this lane needs actually present? A missing tool must report
# UNAVAILABLE, never FAIL: "you have not installed anything yet" and "your code
# is broken" are different states, and conflating them is how a red gate starts
# getting ignored. Probed at run time, not at generation time, so a lane starts
# working the moment its tool is installed, with no regeneration.
tool_present() {
  local cmd="$1"
  # shellcheck disable=SC2086 # Intentional tokenization of a lane command.
  set -- $cmd
  case "$1" in
    ears_check|ste_check|crypto_check) return 0 ;;         # shell functions
    pnpm|npm|yarn)
      command -v "$1" >/dev/null 2>&1 || return 1
      [ "${2:-}" = exec ] || return 0                      # e.g. "pnpm audit"
      # Check the local bin directly. `pnpm exec X --version` can resolve X
      # over the network, so it reports available for a package that is not
      # installed, and the lane then FAILs instead of reporting UNAVAILABLE.
      [ -x "node_modules/.bin/$3" ] || command -v "$3" >/dev/null 2>&1 ;;
    *) command -v "$1" >/dev/null 2>&1 ;;
  esac
}

lane() { # lane <name> <command> [warn-only]
  local name="$1" cmd="$2" warnonly="${3:-}"
  if [ -z "$cmd" ] || ! tool_present "$cmd"; then
    if waived "$name"; then printf '  %-14s %sWAIVED%s\n' "$name" "$c_warn" "$c_off"; return; fi
    local why="no tool wired for this stack"
    if [ -n "$cmd" ]; then
      # Name the tool that is actually missing. For "pnpm exec vitest run" the
      # missing thing is vitest, not pnpm, and saying pnpm sends people to fix
      # the wrong thing.
      # shellcheck disable=SC2086 # Intentional tokenization to name the tool.
      set -- $cmd
      local missing="$1"; [ "${2:-}" = exec ] && missing="$3"
      why="not installed: $missing"
    fi
    printf '  %-14s %sUNAVAILABLE%s (%s)\n' "$name" "$c_warn" "$c_off" "$why"
    UNAVAIL=$((UNAVAIL+1)); return
  fi
  RAN=$((RAN+1))
  local output_file out rc
  output_file=$(mktemp "${TMPDIR:-/tmp}/qgate-lane.XXXXXX") || {
    printf 'qgate: unable to create lane output file\n' >&2
    FAILED=$((FAILED+1)); return
  }
  run_lane_command "$cmd" "$output_file"
  rc=$?
  out=$(head -c "${LANE_OUTPUT_BYTES:-12000}" "$output_file" 2>/dev/null || true)
  rm -f "$output_file"
  if [ $rc -eq 0 ]; then
    if [ "$name" = crypto ] && [ -n "$out" ]; then printf '%s\n' "$out" | sed 's/^/      /'; fi
    printf '  %-14s %sPASS%s\n' "$name" "$c_pass" "$c_off"
  elif [ $rc -eq 77 ]; then
    # 77 = the check ran but found nothing in scope to verify. That is not a
    # pass; it is the same state as a missing tool.
    printf '  %-14s %sUNAVAILABLE%s (nothing in scope to check)\n' "$name" "$c_warn" "$c_off"
    RAN=$((RAN-1)); UNAVAIL=$((UNAVAIL+1))
  elif [ -n "$warnonly" ]; then
    printf '  %-14s %sWARN%s\n' "$name" "$c_warn" "$c_off"
    printf '%s\n' "$out" | sed 's/^/      /' | head -12
  else
    printf '  %-14s %sFAIL%s\n' "$name" "$c_fail" "$c_off"
    printf '%s\n' "$out" | sed 's/^/      /' | head -30
    FAILED=$((FAILED+1))
  fi
}

# slot <display> <SLOT> [warn-only]: run every stack's command for this slot.
# A polyglot repo runs every matched stack's lane; if no stack wired one, the
# slot reports a single UNAVAILABLE row.
slot() {
  local display="$1" slotname="$2" warnonly="${3:-}" any=0 s v
  for s in $QG_STACKS; do
    eval "v=\${L_${slotname}_${s}:-}"
    [ -n "$v" ] || continue
    any=1
    lane "$display($s)" "$v" "$warnonly"
  done
  [ $any = 1 ] || lane "$display" ""
}

# unit-chg falls back per stack to that stack's full unit suite.
slot_unit_changed() {
  local any=0 s v
  for s in $QG_STACKS; do
    eval "v=\${L_UNIT_CHANGED_${s}:-\${L_UNIT_${s}:-}}"
    [ -n "$v" ] || continue
    any=1
    lane "unit-chg($s)" "$v"
  done
  [ $any = 1 ] || lane "unit-chg" ""
}

# EARS: requirement lines must match an EARS pattern. Scoped to MARKED
# requirements only: lines inside a "## Requirements" section, or lines
# starting with "REQ-". Prose that happens to contain shall/must/should is
# not a requirement, and a lane that cries wolf gets switched off. A spec
# tree with no marked requirements returns 77 (UNAVAILABLE, never PASS):
# zero checked lines verified nothing.
ears_check() {
  [ "${EARS_ENFORCE:-0}" = 1 ] || return 0
  local bad=0 any=0 f line inreq isreq
  for d in $EARS_PATHS; do
    [ -d "$d" ] || continue
    while IFS= read -r f; do
      inreq=0
      while IFS= read -r line; do
        case "$line" in
          '## Requirements'*) inreq=1; continue ;;
          '#'*) inreq=0 ;;
        esac
        isreq=0
        [ $inreq = 1 ] && isreq=1
        case "$line" in REQ-*) isreq=1 ;; esac
        [ $isreq = 1 ] || continue
        printf '%s' "$line" | grep -qiE '\b(shall|must|should)\b' || continue
        any=1
        printf '%s' "$line" | grep -qiE '^[[:space:]]*(REQ-[A-Za-z0-9_.-]+:?[[:space:]]*)?[-*0-9.]*[[:space:]]*(The|When|While|If|Where|Once)\b' && continue
        echo "$f: not EARS: ${line:0:90}"; bad=1
      done < "$f"
    done < <(find "$d" -name '*.md' 2>/dev/null)
  done
  [ $any = 1 ] || return 77
  return $bad
}

# ASD-STE100: sentence-length heuristic with a domain allowlist. Blocking when
# STE_ENFORCE=1 (the default: AI-authored prose is held to it), warn-only
# otherwise. Zero files in scope returns 77 (UNAVAILABLE, never PASS).
ste_check() {
  local bad=0 any=0 f
  for p in $STE_PATHS; do
    while IFS= read -r f; do
      case "$f" in
        "$p"|"$p"/*.md) ;;
        *) continue ;;
      esac
      any=1
      awk -v maxw="$STE_MAX_WORDS_DESCRIPTIVE" -v file="$f" '
        /^```/ {inblock=!inblock} inblock {next}
        {
          n=split($0, s, /[.!?]/)
          for (i=1;i<=n;i++) { w=split(s[i], junk, /[ \t]+/); if (w>maxw) { print file ": " w " words: " substr(s[i],1,70); bad=1 } }
        } END {exit bad}' "$f" || bad=1
    done < <(repo_files)
  done
  [ $any = 1 ] || return 77
  return $bad
}

# Crypto: banned primitives anywhere, algorithm names outside the crypto module,
# and unseeded randomness in security-relevant files. Grep-based and therefore
# blunt, so it is scoped tightly: a lane that cries wolf gets switched off.
crypto_check() {
  [ "${CRYPTO_ENFORCE:-0}" = 1 ] || return 0
  local bad=0 files hit references
  # Exclude the gate's own files. They contain every banned primitive and every
  # algorithm name by construction, as the rule definitions, and a linter that
  # flags its own ruleset reports a permanent false positive that masks the real
  # ones underneath it.
  files=$(repo_files)
  references=$(printf '%s\n' "${CRYPTO_REFERENCE_PATHS:-}" | tr ' ' '\n' | sed '/^$/d')
  if [ -n "$references" ]; then
    echo "crypto reference exclusions:"
    printf '%s\n' "$references" | sed 's/^/  /'
    files=$(printf '%s\n' "$files" | grep -Fvx -f <(printf '%s\n' "$references") || true)
  else
    echo "crypto reference exclusions: none"
  fi
  [ -n "$files" ] || return 0

  for p in $CRYPTO_BANNED; do
    hit=$(printf '%s\n' "$files" | xargs grep -lniE "(createHash|hashlib|Digest|hmac|password_hash|import|require)[^\n]{0,40}\b$p\b" 2>/dev/null || true)
    [ -n "$hit" ] && { echo "banned primitive '$p': $(printf '%s' "$hit" | tr '\n' ' ')"; bad=1; }
  done

  # Algorithm literals outside the crypto module: the thing that makes a
  # future migration a repo-wide edit instead of a one-file change.
  local outside
  outside=$(printf '%s\n' "$files" | grep -Ev "^($(printf '%s' "$CRYPTO_MODULE" | tr ' ' '|'))/" || true)
  if [ -n "$outside" ]; then
    hit=$(printf '%s\n' "$outside" | xargs grep -lnE "\b(aes-256-gcm|AES_256_GCM|AEGIS|ML-KEM|ML_KEM|ML-DSA|SLH-DSA|X25519|RSA-OAEP|PBKDF2|HKDF)\b" 2>/dev/null || true)
    [ -n "$hit" ] && { echo "algorithm name outside crypto module: $(printf '%s' "$hit" | tr '\n' ' ')"; bad=1; }
  fi

  # Non-cryptographic randomness in files that name a security concern.
  hit=$(printf '%s\n' "$files" | grep -iE '(token|secret|key|nonce|salt|session|auth)' \
        | xargs grep -lnE '(Math\.random\(\)|[^a-z_]rand\(\)|random\.random\(\))' 2>/dev/null || true)
  [ -n "$hit" ] && { echo "non-crypto randomness in security file: $(printf '%s' "$hit" | tr '\n' ' ')"; bad=1; }

  return $bad
}

echo "Quality gate: $TIER   stacks: $STACKS"
[ -n "$WAIVERS" ] && printf '%sactive waivers: %s%s\n' "$c_warn" "$WAIVERS" "$c_off"
echo

echo "T1 fast"
slot format   FMT
slot lint     LINT
slot types    TYPES
slot secrets  SECRETS
slot_unit_changed

if [ "$TIER" = --merge ] || [ "$TIER" = --deep ]; then
  echo
  echo "T2 merge"
  slot unit       UNIT
  slot acceptance ACCEPT
  slot coverage   COVERAGE
  slot complexity COMPLEXITY
  lane ears       "ears_check"
  lane crypto     "crypto_check"
  slot sast       SAST
  slot deps       DEPS
  slot fuzz-smoke FUZZ_SMOKE
  # STE blocks when enforced (AI-authored prose, user law); warns otherwise.
  if [ "${STE_ENFORCE:-0}" = 1 ]; then lane ste "ste_check"; else lane ste "ste_check" warn; fi
fi

if [ "$TIER" = --deep ]; then
  echo
  echo "T3 deep"
  slot mutation  MUTATION
  slot fuzz-deep FUZZ_DEEP
  slot dast      DAST
  echo
  echo "  ASVS L${ASVS_LEVEL}: verify the checklist in docs/security/asvs-l${ASVS_LEVEL}.md"
  echo "  ${c_dim}(machine lanes above cover part of it; the rest is a reviewed checklist)${c_off}"
fi

echo
echo "------------------------------------------------------------"
if [ $FAILED -gt 0 ]; then
  printf '%sGATE RED%s: %d lane(s) failed, %d ran\n' "$c_fail" "$c_off" "$FAILED" "$RAN"; exit 1
fi
# A gate that ran nothing has verified nothing. Reporting GREEN here would be
# the exact lie this gate exists to prevent, so it is never a pass at any tier.
if [ $RAN -eq 0 ]; then
  printf '%sNOTHING VERIFIED%s: 0 lanes ran. Install a tool or waive explicitly; this is not a pass.\n' "$c_fail" "$c_off"; exit 3
fi
if [ "$TIER" != --fast ] && [ $UNAVAIL -gt 0 ]; then
  printf '%sGATE NOT GREEN%s: %d lane(s) UNAVAILABLE. Wire the tool or add a dated waiver.\n' "$c_warn" "$c_off" "$UNAVAIL"; exit 2
fi
printf '%sGATE GREEN%s: %d lane(s) passed, %d unavailable\n' "$c_pass" "$c_off" "$RAN" "$UNAVAIL"
